version: '3.3'
services:
  study-db:
    image: postgres:13
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users_info
    restart: always
