
# Build jar with gradle
name: Build Java 

on:
  push:
    branches: [ "master" ]

jobs:
  jwt-service-build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      
      - name: Build with Gradle
        working-directory: ./jwt-service
        run: ./gradlew build
          
    
