
# Build jar with gradle
name: Build Java 

on:
  push:
    branches: [ "master" ]

jobs:
  jwt-service-build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Clone repository
        uses: actions/checkout@v3
        
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Build with Gradle
        working-directory: ./jwt-service
        run: |
              chmod +x ./gradlew
              ./gradlew build

  db-service-build:
    runs-on: ubuntu-latest

    steps:

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        working-directory: ./db-service
        run: |
          chmod +x ./gradlew
          ./gradlew build  
